# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bflanagin/Work/os-autoinst

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bflanagin/Work/os-autoinst

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"openvswitch\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bflanagin/Work/os-autoinst/CMakeFiles /home/bflanagin/Work/os-autoinst//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bflanagin/Work/os-autoinst/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named videoencoder

# Build rule for target.
videoencoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 videoencoder
.PHONY : videoencoder

# fast build rule for target.
videoencoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/videoencoder.dir/build.make CMakeFiles/videoencoder.dir/build
.PHONY : videoencoder/fast

#=============================================================================
# Target rules for targets named generate-install-versions

# Build rule for target.
generate-install-versions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate-install-versions
.PHONY : generate-install-versions

# fast build rule for target.
generate-install-versions/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/generate-install-versions.dir/build.make CMakeFiles/generate-install-versions.dir/build
.PHONY : generate-install-versions/fast

#=============================================================================
# Target rules for targets named check-pkg-build

# Build rule for target.
check-pkg-build: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-pkg-build
.PHONY : check-pkg-build

# fast build rule for target.
check-pkg-build/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check-pkg-build.dir/build.make CMakeFiles/check-pkg-build.dir/build
.PHONY : check-pkg-build/fast

#=============================================================================
# Target rules for targets named symlinks

# Build rule for target.
symlinks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 symlinks
.PHONY : symlinks

# fast build rule for target.
symlinks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/symlinks.dir/build.make CMakeFiles/symlinks.dir/build
.PHONY : symlinks/fast

#=============================================================================
# Target rules for targets named install-openvswitch

# Build rule for target.
install-openvswitch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install-openvswitch
.PHONY : install-openvswitch

# fast build rule for target.
install-openvswitch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/install-openvswitch.dir/build.make CMakeFiles/install-openvswitch.dir/build
.PHONY : install-openvswitch/fast

#=============================================================================
# Target rules for targets named test-local

# Build rule for target.
test-local: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-local
.PHONY : test-local

# fast build rule for target.
test-local/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-local.dir/build.make CMakeFiles/test-local.dir/build
.PHONY : test-local/fast

#=============================================================================
# Target rules for targets named test-doc

# Build rule for target.
test-doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-doc
.PHONY : test-doc

# fast build rule for target.
test-doc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-doc.dir/build.make CMakeFiles/test-doc.dir/build
.PHONY : test-doc/fast

#=============================================================================
# Target rules for targets named test-perl-testsuite

# Build rule for target.
test-perl-testsuite: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-perl-testsuite
.PHONY : test-perl-testsuite

# fast build rule for target.
test-perl-testsuite/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-perl-testsuite.dir/build.make CMakeFiles/test-perl-testsuite.dir/build
.PHONY : test-perl-testsuite/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/check.dir/build.make CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named update-deps

# Build rule for target.
update-deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update-deps
.PHONY : update-deps

# fast build rule for target.
update-deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/update-deps.dir/build.make CMakeFiles/update-deps.dir/build
.PHONY : update-deps/fast

#=============================================================================
# Target rules for targets named test-installed-files

# Build rule for target.
test-installed-files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-installed-files
.PHONY : test-installed-files

# fast build rule for target.
test-installed-files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-installed-files.dir/build.make CMakeFiles/test-installed-files.dir/build
.PHONY : test-installed-files/fast

#=============================================================================
# Target rules for targets named tidy-cpp

# Build rule for target.
tidy-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tidy-cpp
.PHONY : tidy-cpp

# fast build rule for target.
tidy-cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tidy-cpp.dir/build.make CMakeFiles/tidy-cpp.dir/build
.PHONY : tidy-cpp/fast

#=============================================================================
# Target rules for targets named debugviewer

# Build rule for target.
debugviewer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 debugviewer
.PHONY : debugviewer

# fast build rule for target.
debugviewer/fast:
	$(MAKE) $(MAKESILENT) -f debugviewer/CMakeFiles/debugviewer.dir/build.make debugviewer/CMakeFiles/debugviewer.dir/build
.PHONY : debugviewer/fast

#=============================================================================
# Target rules for targets named snd2png

# Build rule for target.
snd2png: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snd2png
.PHONY : snd2png

# fast build rule for target.
snd2png/fast:
	$(MAKE) $(MAKESILENT) -f snd2png/CMakeFiles/snd2png.dir/build.make snd2png/CMakeFiles/snd2png.dir/build
.PHONY : snd2png/fast

#=============================================================================
# Target rules for targets named tinycv

# Build rule for target.
tinycv: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinycv
.PHONY : tinycv

# fast build rule for target.
tinycv/fast:
	$(MAKE) $(MAKESILENT) -f ppmclibs/CMakeFiles/tinycv.dir/build.make ppmclibs/CMakeFiles/tinycv.dir/build
.PHONY : tinycv/fast

#=============================================================================
# Target rules for targets named generate_documentation

# Build rule for target.
generate_documentation: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 generate_documentation
.PHONY : generate_documentation

# fast build rule for target.
generate_documentation/fast:
	$(MAKE) $(MAKESILENT) -f doc/CMakeFiles/generate_documentation.dir/build.make doc/CMakeFiles/generate_documentation.dir/build
.PHONY : generate_documentation/fast

videoencoder.o: videoencoder.cpp.o

.PHONY : videoencoder.o

# target to build an object file
videoencoder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/videoencoder.dir/build.make CMakeFiles/videoencoder.dir/videoencoder.cpp.o
.PHONY : videoencoder.cpp.o

videoencoder.i: videoencoder.cpp.i

.PHONY : videoencoder.i

# target to preprocess a source file
videoencoder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/videoencoder.dir/build.make CMakeFiles/videoencoder.dir/videoencoder.cpp.i
.PHONY : videoencoder.cpp.i

videoencoder.s: videoencoder.cpp.s

.PHONY : videoencoder.s

# target to generate assembly for a file
videoencoder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/videoencoder.dir/build.make CMakeFiles/videoencoder.dir/videoencoder.cpp.s
.PHONY : videoencoder.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... check"
	@echo "... check-pkg-build"
	@echo "... generate-install-versions"
	@echo "... generate_documentation"
	@echo "... install-openvswitch"
	@echo "... symlinks"
	@echo "... test-doc"
	@echo "... test-installed-files"
	@echo "... test-local"
	@echo "... test-perl-testsuite"
	@echo "... tidy-cpp"
	@echo "... update-deps"
	@echo "... debugviewer"
	@echo "... snd2png"
	@echo "... tinycv"
	@echo "... videoencoder"
	@echo "... videoencoder.o"
	@echo "... videoencoder.i"
	@echo "... videoencoder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

