---
name: ci
# yamllint disable-line rule:truthy
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Static checks, unit- and integration tests
        run: tools/container_run_ci
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./cover_db/codecov.json
          fail_ci_if_error: true
          verbose: true
  static-check-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test our container definitions
        run: tools/static_check_containers
